import {
  faApple,
  faFacebookF,
  faGoogle,
  faInstagram,
  faTwitter,
  faWhatsapp,
} from '@fortawesome/free-brands-svg-icons';
import {
  faCircle as faCircleRegular,
  faHeart as faHeartRegular,
  faStar as faStarRegular,
  faThumbsUp as faThumbsUpRegular,
} from '@fortawesome/free-regular-svg-icons';
import {
  faAppleAlt,
  faArrowLeft,
  faArrowRight,
  faAward,
  faBars,
  faBolt,
  faBoxOpen,
  faCamera,
  faCarrot,
  faCertificate,
  faCheck,
  faCheckCircle,
  faCheese,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faClock,
  faCloudUploadAlt,
  faCopy,
  faDownload,
  faEdit,
  faEllipsisV,
  faEnvelope,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faFilter,
  faHandshake,
  faHeart,
  faInfoCircle,
  faJar,
  faKey,
  faLeaf,
  faList,
  faLock,
  faMapMarkerAlt,
  faMinus,
  faPaperPlane,
  faPhone,
  faPlus,
  faRedo,
  faSearch,
  faSeedling,
  faShieldAlt,
  faShoppingCart,
  faSignOutAlt,
  faStar,
  faStarHalfAlt,
  faTh,
  faThumbsUp,
  faTimes,
  faTimesCircle,
  faTractor,
  faTruck,
  faUser,
} from '@fortawesome/free-solid-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

/**
 * Curated Font Awesome registry. We import only the icons the templates use so
 * the bundle stays small (importing whole packs adds ~1.5MB). Components refer
 * to icons by these semantic keys via the <Icon /> wrapper.
 */
export const ICONS = {
  // Brand / nav
  seedling: faSeedling,
  search: faSearch,
  cart: faShoppingCart,
  user: faUser,
  bars: faBars,
  filter: faFilter,
  grid: faTh,
  list: faList,
  signOut: faSignOutAlt,
  // Chevrons / arrows
  chevronDown: faChevronDown,
  chevronRight: faChevronRight,
  chevronLeft: faChevronLeft,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  // Categories
  carrot: faCarrot,
  appleAlt: faAppleAlt,
  cheese: faCheese,
  jar: faJar,
  leaf: faLeaf,
  // Ratings / actions
  star: faStar,
  starRegular: faStarRegular,
  starHalf: faStarHalfAlt,
  heart: faHeart,
  heartRegular: faHeartRegular,
  bolt: faBolt,
  plus: faPlus,
  minus: faMinus,
  edit: faEdit,
  trash: faTimesCircle,
  eye: faEye,
  eyeSlash: faEyeSlash,
  copy: faCopy,
  download: faDownload,
  redo: faRedo,
  ellipsisV: faEllipsisV,
  thumbsUp: faThumbsUp,
  thumbsUpRegular: faThumbsUpRegular,
  boxOpen: faBoxOpen,
  // Trust / features
  truck: faTruck,
  shield: faShieldAlt,
  handshake: faHandshake,
  award: faAward,
  certificate: faCertificate,
  tractor: faTractor,
  camera: faCamera,
  upload: faCloudUploadAlt,
  // Location / contact
  mapMarker: faMapMarkerAlt,
  phone: faPhone,
  envelope: faEnvelope,
  lock: faLock,
  key: faKey,
  paperPlane: faPaperPlane,
  // Status
  check: faCheck,
  checkCircle: faCheckCircle,
  circle: faCircle,
  circleRegular: faCircleRegular,
  clock: faClock,
  times: faTimes,
  timesCircle: faTimesCircle,
  info: faInfoCircle,
  warning: faExclamationTriangle,
  // Social (brands)
  google: faGoogle,
  facebook: faFacebookF,
  twitter: faTwitter,
  instagram: faInstagram,
  whatsapp: faWhatsapp,
  apple: faApple,
} satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof ICONS;
